# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class House_rentalItem(scrapy.Item):
    # define the fields for your item here like:
    city = scrapy.Field()
    area = scrapy.Field()
    street = scrapy.Field()
    community = scrapy.Field()
    address = scrapy.Field()
    type = scrapy.Field()
    bd_type = scrapy.Field()
    title = scrapy.Field()
    price = scrapy.Field()
    size = scrapy.Field()
    phone = scrapy.Field()
    contact_url = scrapy.Field()
    shi = scrapy.Field()
    ting = scrapy.Field()
    wei = scrapy.Field()
    orientation = scrapy.Field()
    floor = scrapy.Field()
    subway = scrapy.Field()
    decoration = scrapy.Field()
    house_types = scrapy.Field()
    property_type = scrapy.Field()
    description = scrapy.Field()
    time = scrapy.Field()
    img_url = scrapy.Field()
    name = scrapy.Field()
    url = scrapy.Field()
    form = scrapy.Field()


class House_saleItem(scrapy.Item):
    # define the fields for your item here like:
    city = scrapy.Field()
    area = scrapy.Field()
    street = scrapy.Field()
    community = scrapy.Field()
    address = scrapy.Field()
    type = scrapy.Field()
    bd_type = scrapy.Field()
    rent_type= scrapy.Field()
    title = scrapy.Field()
    pay_method= scrapy.Field()
    price = scrapy.Field()
    size = scrapy.Field()
    phone = scrapy.Field()
    contact_url = scrapy.Field()
    shi = scrapy.Field()
    ting = scrapy.Field()
    wei = scrapy.Field()
    orientation = scrapy.Field()
    floor = scrapy.Field()
    subway = scrapy.Field()
    decoration = scrapy.Field()
    house_types = scrapy.Field()
    description = scrapy.Field()
    time = scrapy.Field()
    img_url = scrapy.Field()
    house_allocation = scrapy.Field()
    name = scrapy.Field()
    url = scrapy.Field()
    form = scrapy.Field()


class Shop_rentalItem(scrapy.Item):
    # define the fields for your item here like:
    area = scrapy.Field()
    street = scrapy.Field()
    address = scrapy.Field()
    type = scrapy.Field()
    bd_type = scrapy.Field()
    width= scrapy.Field()
    length= scrapy.Field()
    high= scrapy.Field()
    manage_status= scrapy.Field()
    title = scrapy.Field()
    price = scrapy.Field()
    pay_method= scrapy.Field()
    size = scrapy.Field()
    phone = scrapy.Field()
    contact_url = scrapy.Field()
    manage_industry = scrapy.Field()
    floor = scrapy.Field()
    description = scrapy.Field()
    time = scrapy.Field()
    img_url = scrapy.Field()
    house_allocation= scrapy.Field()
    name = scrapy.Field()
    category= scrapy.Field()
    url = scrapy.Field()
    form = scrapy.Field()


class Shop_saleItem(scrapy.Item):
    # define the fields for your item here like:
    city = scrapy.Field()
    area = scrapy.Field()
    street = scrapy.Field()
    address = scrapy.Field()
    type = scrapy.Field()
    bd_type = scrapy.Field()
    width = scrapy.Field()
    length = scrapy.Field()
    high = scrapy.Field()
    manage_status = scrapy.Field()
    title = scrapy.Field()
    price = scrapy.Field()
    size = scrapy.Field()
    phone = scrapy.Field()
    contact_url = scrapy.Field()
    manage_industry = scrapy.Field()
    floor = scrapy.Field()
    description = scrapy.Field()
    time = scrapy.Field()
    img_url = scrapy.Field()
    house_allocation = scrapy.Field()
    name = scrapy.Field()
    category = scrapy.Field()
    url = scrapy.Field()
    form = scrapy.Field()

class Office_saleItem(scrapy.Item):
    # define the fields for your item here like:
    city = scrapy.Field()
    area = scrapy.Field()
    street = scrapy.Field()
    address = scrapy.Field()
    type = scrapy.Field()
    bd_type = scrapy.Field()
    title = scrapy.Field()
    price = scrapy.Field()
    size = scrapy.Field()
    phone = scrapy.Field()
    contact_url = scrapy.Field()
    floor = scrapy.Field()
    registered_company = scrapy.Field()
    description = scrapy.Field()
    time = scrapy.Field()
    img_url = scrapy.Field()
    house_allocation = scrapy.Field()
    name = scrapy.Field()
    category = scrapy.Field()
    url = scrapy.Field()
    form = scrapy.Field()

class Office_rentalItem(scrapy.Item):
    # define the fields for your item here like:
    city = scrapy.Field()
    area = scrapy.Field()
    street = scrapy.Field()
    address = scrapy.Field()
    type = scrapy.Field()
    bd_type = scrapy.Field()
    title = scrapy.Field()
    price = scrapy.Field()
    size = scrapy.Field()
    phone = scrapy.Field()
    contact_url = scrapy.Field()
    floor = scrapy.Field()
    registered_company = scrapy.Field()
    description = scrapy.Field()
    time = scrapy.Field()
    img_url = scrapy.Field()
    house_allocation = scrapy.Field()
    name = scrapy.Field()
    category = scrapy.Field()
    url = scrapy.Field()
    form = scrapy.Field()
class Rent_and_purchase_generalItem(scrapy.Item):
    # define the fields for your item here like:
    city = scrapy.Field()
    area = scrapy.Field()
    type = scrapy.Field()
    bd_type = scrapy.Field()
    title = scrapy.Field()
    price = scrapy.Field()
    size = scrapy.Field()
    phone = scrapy.Field()
    contact_url = scrapy.Field()
    description = scrapy.Field()
    time = scrapy.Field()
    name = scrapy.Field()
    url = scrapy.Field()
    form = scrapy.Field()